FROM azpagentinfra/arm:latest AS test
WORKDIR /app
EXPOSE 80


# COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static 

RUN apt update
RUN apt install -y unzip

WORKDIR /app
COPY /src /src

WORKDIR /src
ENTRYPOINT ["./dev.sh"]
