FROM mcr.microsoft.com/dotnet/aspnet:3.1-focal-arm64v8 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:3.1.416-focal-arm64v8 AS build
COPY /src /src
WORKDIR /src
RUN apt update
RUN apt install unzip
ENTRYPOINT ["./dev.sh", "testl0", "Debug", "linux-arm64"]