FROM mcr.microsoft.com/dotnet/sdk:3.1.416-focal-arm64v8 AS test
WORKDIR /app
EXPOSE 80

COPY /src /src
COPY /_downloads /_downloads
COPY /_layout /_layout

WORKDIR /src
RUN apt update -y
# RUN apt install qemu -y qemu-system-arm
# RUN qemu-system-arm -append 'root=/dev/vda console=ttyS0' -drive file='rootfs.ext2.qcow2,if=virtio,format=qcow2'  -enable-kvm -kernel 'bzImage' -nographic
RUN apt install unzip
ENTRYPOINT ["./dev.sh"]
