FROM mcr.microsoft.com/dotnet/aspnet:3.1-focal-arm64v8 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:3.1.416-focal-arm64v8 AS build
COPY /src /src
WORKDIR /src
RUN ./dev.sh l
RUN ./dev.sh l0
ENTRYPOINT ./dev.sh l0
